version: '2'
services:
    taskmanager-app:
        image: taskmanager
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://taskmanager-postgresql:5432/taskmanager
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    taskmanager-postgresql:
        extends:
            file: postgresql.yml
            service: taskmanager-postgresql
