version: '2'
services:
    taskmanager-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/TaskManager/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=TaskManager
            - POSTGRES_PASSWORD=111
        ports:
            - 5432:5432
    adminer:
        image: adminer
        restart: always
        ports:
            - 8099:8080
